default namespace = inherit
namespace       a = "http://relaxng.org/ns/compatibility/annotations/1.0"
namespace     rng = "http://relaxng.org/ns/structure/1.0"
datatypes     xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

# Extends node
node-content &=
    element color { color-content }?
  & element position { position-content }?
  & element size { size-content }?
  & element shape { node-shape-content }?

# Extend edge
edge-content &=
    element color { color-content }?
  & element thickness { thickness-content }?
  & element shape { edge-shape-content }?

# Color
color-content =
    ((attribute r { color-channel }
  & attribute g { color-channel }
  & attribute b { color-channel })
    | attribute hex { xsd:token })
  & attribute a { alpha-channel }?

# Position
position-content =
    attribute x { xsd:float }
  & attribute y { xsd:float }
  & attribute z { xsd:float }?

# Size
size-content =
    attribute value { size-type }

# Thickness
thickness-content =
    attribute value { thickness-type }

# Node shape
node-shape-content =
    attribute value { node-shape-type }
  & attribute uri { xsd:anyURI }?

# Edge shape
edge-shape-content =
    attribute value { edge-shape-type }

# Color
color-channel = 
    xsd:nonNegativeInteger { maxInclusive = "255" }

# Alpha Channel
alpha-channel = [ a:defaultValue = "1.0" ] 
    xsd:float { minInclusive = "0.0" maxInclusive = "1.0" }

# Size
size-type = [ a:defaultValue = "1.0" ] 
    xsd:float { minInclusive = "0.0"}

# Thickness
thickness-type = [ a:defaultValue = "1.0" ] 
    xsd:float { minInclusive = "0.0"}

# Node shape
node-shape-type =  [ a:defaultValue = "disc" ] 
                        # Byte value in Gephi
    string "disc"     | # 0000 0000 0
    string "triangle" | # 0000 0001 1
    string "square"   | # 0000 0010 2
    string "diamond"  | # 0000 0011 3 
    string "star"     | # 0000 0100 4
    string "pentagon" | # 0000 0101 5 
    string "hexagon"  | # 0000 0110 6
    string "cross"    | # 0000 0111 7 
    string "custom_1" | # 1000 0000 128
    string "custom_2" | # 1000 0001 129
    string "custom_3" | # 1000 0010 130
    string "custom_4" | # 1000 0011 131
    string "custom_5" | # 1000 0100 132
    string "custom_6" | # 1000 0101 133
    string "custom_7" | # 1000 0110 134
    string "custom_8"   # 1000 0111 135

# Edge shape
edge-shape-type =  [ a:defaultValue = "solid" ] 
                          # Byte value in Gephi
    string "solid"    |   # 0000 0000 0
    string "dotted"   |   # 0000 0001 1
    string "dashed"   |   # 0000 0010 2
    string "double"   |   # 0000 0011 3
    string "custom_1" |   # 1000 0000 128
    string "custom_2" |   # 1000 0001 129
    string "custom_3" |   # 1000 0010 130
    string "custom_4" |   # 1000 0011 131
    string "custom_5" |   # 1000 0100 132
    string "custom_6" |   # 1000 0101 133
    string "custom_7" |   # 1000 0110 134
    string "custom_8"     # 1000 0111 135
